class ApiException(Exception):
    def __init__(self, code, error_message, result=None):
        self.result = result
        self.code = code
        self.error_message = error_message

#SUCCESS MESSAGE
USER_CREATED = "USER_CREATE_SUCCUESS"
SUCCESS = "SUCCESS"


#FAILED MESSAGE

## USER CREATE FAILED MESSAGE
INVALID_INPUT_FIRST_NAME = "INVALID_INPUT_FIRST_NAME"
INVALID_INPUT_LAST_NAME = "INVALID_INPUT_LAST_NAME"
INVALID_INPUT_PASSWORD = "INVALID_INPUT_PASSWORD"
INVALID_INPUT_DATE_OF_BIRTH = "INVALID_INPUT_DATE_OF_BIRTH"
INVALID_INPUT_PHONE_NUMBER = "INVALID_INPUT_PHONE_NUMBER"
INVALID_INPUT_EMAIL = "INVALID_INPUT_EMAIL"
DUPLICATED_EMAIL = "DUPLICATED_EMAIL"
USER_NOT_FOUND = "USER_NOT_FOUND"  
PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
INVALID_INPUT_START_DATE = "INVALID_INPUT_START_DATE"
INVALID_INPUT_END_DATE = "INVALID_INPUT_END_DATE"
NOT_ACCOMMODATEION_ID = "NOT_ACCOMMODATEION_ID"
NOT_START_DATE = "NOT_START_DATE"
NOT_END_DATE = "NOT_END_DATE"
NOT_USER = "NOT_USER"
NOT_START_DATE = "NOT_START_DATE"
NOT_END_DATE = "NOT_END_DATE"
NOT_TOTAL_PRICE = "NOT_TOTAL_PRICE"
NOT_ACCOMMODATION_PRICE = "NOT_ACCOMMODATION_PRICE"
NOT_SERVICE_FEE = "NOT_SERVICE_FEE"
NOT_CLEANING_FEE = "NOT_CLEANING_FEE"
INVALID_USER = "INVALID_USER"
USER_HAS_BEEN_DELETED = "USER_HAS_BEEN_DELETED"
LOGIN_REQUIRED = "LOGIN_REQUIRED"
INVALID_TOKEN = "INVALID_TOKEN"
NOT_MYPAGE_STATUS = "NOT_MYPAGE_STATUS"
NOT_MYPAGE_STATUS
